# Generated by Django 5.2.4 on 2025-07-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="completed_images/"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="defaults/default_thumb.jpg",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
