# Generated by Django 5.2.4 on 2025-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_blogpost_todo_completed_image_todo_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="todo/completed_images/"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="todo/no_image/no_image.jpeg",
                null=True,
                upload_to="todo/thumbnails/",
            ),
        ),
    ]
